export const ProfilesList = [
    {
        accountId: "1",
        profileId: "1",
        country: "USA",
        marketplace: "Amazon",
    },
    {
        accountId: "1",
        profileId: "2",
        country: "UK",
        marketplace: "eBay",
    },
    {
        accountId: "1",
        profileId: "3",
        country: "Germany",
        marketplace: "Alibaba",
    },
    {
        accountId: "2",
        profileId: "4",
        country: "Spain",
        marketplace: "Allegro",
    },
    {
        accountId: "2",
        profileId: "5",
        country: "Switzerland",
        marketplace: "OLX",
    },
    {
        accountId: "3",
        profileId: "6",
        country: "Singapore",
        marketplace: "Zalando",
    },
    {
        accountId: "4",
        profileId: "7",
        country: "Mexico",
        marketplace: "B2W",
    },
    {
        accountId: "4",
        profileId: "8",
        country: "Malaysia",
        marketplace: "Cdiscount",
    },
    {
        accountId: "5",
        profileId: "9",
        country: "Poland",
        marketplace: "Flipkart",
    },
    {
        accountId: "5",
        profileId: "10",
        country: "Romania",
        marketplace: "Best Buy",
    },
    {
        accountId: "6",
        profileId: "11",
        country: "Ireland",
        marketplace: "Target",
    },
    {
        accountId: "7",
        profileId: "12",
        country: "Brazil",
        marketplace: "Trade Me",
    },
    {
        accountId: "7",
        profileId: "13",
        country: "Argentina",
        marketplace: "Cdiscount",
    },
    {
        accountId: "7",
        profileId: "14",
        country: "Greece",
        marketplace: "Shopify",
    },
    {
        accountId: "8",
        profileId: "15",
        country: "France",
        marketplace: "Amazon",
    },
    {
        accountId: "8",
        profileId: "16",
        country: "South Korea",
        marketplace: "Walmart",
    },
    {
        accountId: "9",
        profileId: "17",
        country: "Denmark",
        marketplace: "Fnac",
    },
    {
        accountId: "10",
        profileId: "18",
        country: "Japan",
        marketplace: "eBay",
    },
    {
        accountId: "10",
        profileId: "19",
        country: "India",
        marketplace: "JD.com",
    },
    {
        accountId: "10",
        profileId: "20",
        country: "Turkey",
        marketplace: "Walmart",
    },
    {
        accountId: "11",
        profileId: "21",
        country: "Czech Republic",
        marketplace: "Amazon",
    },
    {
        accountId: "11",
        profileId: "22",
        country: "Greece",
        marketplace: "MercadoLibre",
    },
    {
        accountId: "12",
        profileId: "23",
        country: "Vietnam",
        marketplace: "Cdiscount",
    },
    {
        accountId: "13",
        profileId: "24",
        country: "China",
        marketplace: "Lazada",
    },
    {
        accountId: "13",
        profileId: "25",
        country: "Brazil",
        marketplace: "Etsy",
    },
    {
        accountId: "14",
        profileId: "26",
        country: "UK",
        marketplace: "Flipkart",
    },
    {
        accountId: "14",
        profileId: "27",
        country: "Belgium",
        marketplace: "Cdiscount",
    },
    {
        accountId: "14",
        profileId: "28",
        country: "Portugal",
        marketplace: "Allegro",
    },
    {
        accountId: "15",
        profileId: "29",
        country: "Singapore",
        marketplace: "Lazada",
    },
    {
        accountId: "15",
        profileId: "30",
        country: "Malaysia",
        marketplace: "Target",
    },

    {
        accountId: "16",
        profileId: "31",
        country: "Argentina",
        marketplace: "B2W",
    },
    {
        accountId: "17",
        profileId: "32",
        country: "Netherlands",
        marketplace: "Flipkart",
    },
    {
        accountId: "17",
        profileId: "33",
        country: "Canada",
        marketplace: "OLX",
    },
    {
        accountId: "18",
        profileId: "34",
        country: "New Zealand",
        marketplace: "JD.com",
    },
    {
        accountId: "18",
        profileId: "35",
        country: "Greece",
        marketplace: "Best Buy",
    },
    {
        accountId: "18",
        profileId: "36",
        country: "Sweden",
        marketplace: "Alibaba",
    },

    {
        accountId: "19",
        profileId: "37",
        country: "Hungary",
        marketplace: "Walmart",
    },
    {
        accountId: "20",
        profileId: "38",
        country: "Singapore",
        marketplace: "Zalando",
    },
    {
        accountId: "20",
        profileId: "39",
        country: "USA",
        marketplace: "Allegro",
    },
    {
        accountId: "20",
        profileId: "40",
        country: "Canada",
        marketplace: "Rakuten",
    },
];
